version: '3.8'

services:
  # Node.js Backend
  event-tracker:
    image: node:16
    container_name: event-tracker
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
    depends_on:
      - clickhouse
    command: sh -c "npm install && node server.js"

  # ClickHouse Database
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=event_tracker
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - event-tracker

# Volumes
volumes:
  clickhouse_data: