# Generated by Django 5.2.3 on 2025-06-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoai', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Notes',
        ),
    ]
